### ISSUE TITLE
Attribute 'sourceAttributeMetaDatas' of entity 'AttributeMapping' cannot have more than 255 characters

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#5152] opened 2016-08-11 07:52 UTC
#### Reproduce
1. Upload this target model: https://drive.google.com/open?id=0B8iNw4kI1MA2NzRRNTRqeWNUa2c
2. Upload this source model: https://drive.google.com/open?id=0B8iNw4kI1MA2bXhlTmwyeWgtbU0
3. Upload this CSV file:
https://drive.google.com/open?id=0B8iNw4kI1MA2Rl9TNFhvVGd6X2c
4. Create mapping project: 
target = eu_bbmri_eric_collections
source = ldap_collection
5. Try to map the materials attribute (mref) with these source attributes (booleans):
-materialStoredDNA'
-materialStoredPlasma
-materialStoredSerum
-materialStoredUrine
-materialStoredSaliva
-materialStoredFaeces
-materialStoredOther
-materialStoredRNA
-materialStoredBlood
-materialStoredImmortalizedCL
-materialStoredIsolatedPathogen
-materialStoredTissueFrozen
-materialStoredTissueFFPE
6. Add algorithm and save the mapping:

materials = []

if ($('materialStoredDNA').value() === true){
    materials.push("DNA");
}else if($('materialStoredPlasma').value() === true){
    materials.push("PLASMA");
}else if($('materialStoredSerum').value() === true){
    materials.push("SERUM");
} else if($('materialStoredUrine').value() === true){
    materials.push("URINE");
} else if($('materialStoredSaliva').value() ===true){
    materials.push("SALIVA");
} else if($('materialStoredFaeces').value() ===true){
    materials.push("FAECES");
}else if($('materialStoredOther').value() ===true){
    materials.push("OTHER");
}else if($('materialStoredRNA').value() ===true){
    materials.push("RNA");
}else if($('materialStoredBlood').value() ===true){
    materials.push("BLOOD");
}else if($('materialStoredImmortalizedCL').value() ===true){
    materials.push("CELL_LINES");
}else if($('materialStoredIsolatedPathogen').value() ===true){
   materials.push("PATHOGEN");
}else if($('materialStoredTissueFrozen').value() ===true){
    materials.push("TISSUE_FROZEN");
}else if($('materialStoredTissueFFPE').value() ===true){
    materials.push("TISSUE_PARAFFIN_EMBEDDED");
}else{
    materials.push("NAV");
}
materials;

#### Expected
Mapped attribute (from booleans to mref).

#### Observed
Error! An error occurred. Please contact the administrator.
Message:Invalid string value 'materialStoredDNA,materialStoredPlasma,materialStoredSerum,materialStoredUrine,materialStoredSaliva,materialStoredFaeces,materialStoredOther,materialStoredRNA,materialStoredBlood,materialStoredImmortalizedCL,materialStoredIsolatedPathogen,materialStoredTissueFrozen,materialStoredTissueFFPE' for attribute 'sourceAttributeMetaDatas' of entity 'AttributeMapping'.Value must be less than or equal to 255 characters

**Comment by Mark-de-Haan** [comment] 2016-08-11 07:57
Duplicate of #5151

**Comment by dennishendriksen** [comment] 2016-08-17 14:21
Solved in 2.0-RC

**Closed** 2016-08-17 14:23 UTC
Labels: 1.21.4, app-bbmri-nl, bug, molgenis-data-mapper
