### ISSUE TITLE
loading invalid group permission data results in infinite spinner

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6632] opened 2017-09-13 09:24 UTC
### How to Reproduce
Upload group authority and group data, with wrong id for group "All users", use Add/update
[permission_config.xlsx](https://github.com/molgenis/molgenis/files/1298888/permission_config.xlsx)

### Expected behavior
Error: Unknown xref value 'aaaacw7gydwof6qwh3l2atiaaq' for attribute 'Group' of entity 'sys_sec_GroupAuthority'.

### Observed behavior
Infinite spinner, with correct stacktrace in log:
```
ERROR o.m.d.importer.emx.EmxImportService - Error handling EmxImportJob
org.molgenis.data.validation.MolgenisValidationException: Unknown xref value 'aaaacw7gydwof6qwh3l2atiaaq' for attribute 'Group' of entity 'sys_sec_GroupAuthority'.
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.translateForeignKeyViolation(PostgreSqlExceptionTranslator.java:342)
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:112)
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:73)
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:61)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:662)
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:950)
	at org.molgenis.data.postgresql.PostgreSqlRepository.lambda$addBatching$3(PostgreSqlRepository.java:445)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at org.molgenis.data.postgresql.PostgreSqlRepository.addBatching(PostgreSqlRepository.java:433)
	at org.molgenis.data.postgresql.PostgreSqlRepository.add(PostgreSqlRepository.java:256)
	at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
	at org.molgenis.data.cache.l1.L1CacheRepositoryDecorator.add(L1CacheRepositoryDecorator.java:53)
	at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
	at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
	at org.molgenis.data.index.IndexActionRepositoryDecorator.add(IndexActionRepositoryDecorator.java:83)
	at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
	at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
	at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
	at org.molgenis.data.validation.RepositoryValidationDecorator.add(RepositoryValidationDecorator.java:79)
	at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
	at org.molgenis.data.RepositorySecurityDecorator.add(RepositorySecurityDecorator.java:183)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.lambda$add$19(TransactionalRepositoryDecorator.java:192)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.add(TransactionalRepositoryDecorator.java:192)
	at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
	at org.molgenis.data.importer.emx.ImportWriter.insertIntoRepo(ImportWriter.java:659)
	at org.molgenis.data.importer.emx.ImportWriter.update(ImportWriter.java:555)
	at org.molgenis.data.importer.emx.ImportWriter.importData(ImportWriter.java:252)
	at org.molgenis.data.importer.emx.ImportWriter.doImport(ImportWriter.java:93)
	at org.molgenis.data.importer.emx.ImportWriter$$FastClassBySpringCGLIB$$df3d0c02.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at org.molgenis.data.importer.emx.ImportWriter$$EnhancerBySpringCGLIB$$3e78fbd3.doImport(<generated>)
	at org.molgenis.data.importer.emx.EmxImportService.doImport(EmxImportService.java:82)
	at org.molgenis.data.importer.emx.EmxImportService.doImport(EmxImportService.java:69)
	at org.molgenis.data.importer.ImportJob.run(ImportJob.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dennishendriksen** [comment] 2017-09-20 08:53
Cannot reproduce on molgenis/master. This issue has the same cause as #6595 which was fixed in 5.2.0-SNAPSHOT.

**Closed by dennishendriksen** 2017-09-20 08:53 UTC
Labels: 5.1.0, bug
