### ISSUE TITLE
Can not delete row from Localization table in data explorer

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis#8791] opened 2019-12-04 11:32 UTC
### How to Reproduce
- Sign in to https://lifelines.dev.molgenis.org/ as admin
- Open the Localization table in the dataexplorer
- delete row with auto generated key ( for example: aaaac3wqrnr7cbudfj5hzbyaai) 
### Expected behavior
Row is deleted

### Observed behavior
Row is not deleted, messages is show at the top of the page:
 'Error! Unknown error'

**Comment by dennishendriksen** [comment] 2020-01-06 07:29
Can't reproduce because the table doesn't contain any entities with auto generated identifiers. Removing a random row in the table on my local machine works.

**Comment by dennishendriksen** [comment] 2020-01-16 12:11
@connoratrug *bump* how to reproduce?

**Comment by mswertz** [comment] 2020-02-04 17:21
@connoratrug if you want this fixed speak now otherwise it will not be fixed in current release.
Please comment.

**Comment by connoratrug** [comment] 2020-02-05 08:33
That fine, i reported the issue as signal to improve the app, it's not a blocking issue for me now

**Comment by dennishendriksen** [comment] 2020-02-05 09:17
@connoratrug see previous comments. how to reproduce? else the issue will closed.

**Closed** 2020-02-07 07:06 UTC
Labels: 8.2, bug
