### ISSUE TITLE
Visible attributes can be added to invisible compound which causes unclear behaviour

### ISSUE THREAD

**Issue by aneashodselmans** [molgenis/molgenis#7671] opened 2018-08-06 13:52 UTC
When I have invisible compounds, child attributes that are set to "visible = true" are not shown in the data explorer

### How to Reproduce
1) Upload the following file via the advanced importer: 
[emx solveRD1 def.xlsx](https://github.com/molgenis/molgenis/files/2262777/emx.solveRD1.def.xlsx)
2) select "data-manual" in the data explorer
3) look at "data item selection", only one attribute is shown -> the ID
4) Click on metadatamanager to view the entire metadata structure

### Expected behavior
Upload fails with a error message stating that the metadata structure is inconsistent

**Comment by bartcharbon** [comment] 2018-08-16 10:30
The attributes are not shown in the data item selection because the visibility of the compound is set to false. 

One could argue that the importer and metadatamanager should give an error when visible attributes are added to a invisible compound.

I propose not to fix this for 7.0.0

**Comment by marikaris** [comment] 2018-08-17 06:13
This is not a bug it's a feature. The default of "visible" is TRUE. If you make it impossible to put visible attributes in invisible compounds, you have to set every bit of very complex EMX files to TRUE, rather than making a whole block invisible by making its parent invisible. For instance with large questionnaire structures I use it (when previous question is false, make next block invisible), which makes everything a bit more structured, understandable and readable.

**Comment by LuukDijkhuis** [comment] 2018-08-17 07:02
sounds plausible. discussed and we're closing it

**Closed by LuukDijkhuis** 2018-08-17 07:02 UTC
Labels: 7.0.0-RC, bug
