### ISSUE TITLE
Columns tooltip stays open in the Data Explorer

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5233] opened 2016-08-31 19:10 UTC
#### Reproduce
Hover the column name and push the sort option.

#### Expected
After leaving the region the tooltip should be disappeared

#### Observed
Tooltips stays on

![screen shot 2016-08-31 at 5 29 35 pm](https://cloud.githubusercontent.com/assets/5586255/18142848/a919512a-6fbf-11e6-98c7-1d3001e2ce82.png)

**Comment by bartcharbon** [comment] 2016-09-01 07:31
Duplicate of #4744

**Closed by bartcharbon** 2016-09-01 07:31 UTC
Labels: master
