### ISSUE TITLE
When I want to add or edit a row in the BBMRI eric model in the dataexplorer I get an error

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6998] opened 2017-12-07 12:09 UTC
### How to Reproduce
Upload: 
[eric-tommy.xlsx](https://github.com/molgenis/molgenis/files/1538961/eric-tommy.xlsx)
Go to the collections table
Click on the plus to add a row

### Expected behavior
I don't retrieve weird errors

### Observed behavior
![screen shot 2017-12-07 at 13 04 24](https://user-images.githubusercontent.com/10075439/33714440-360ed43c-db4f-11e7-972c-0f3f6495eb07.png)

![screen shot 2017-12-07 at 13 05 10](https://user-images.githubusercontent.com/10075439/33714570-b9286068-db4f-11e7-9a9f-a2e89ff01b56.png)

and a beautifull infinite spinner in my form:
![screen shot 2017-12-07 at 13 25 12](https://user-images.githubusercontent.com/10075439/33715222-1cc9445a-db52-11e7-9d94-6a181003a7c6.png)

**Comment by dennishendriksen** [comment] 2017-12-08 13:56
Duplicate of #6608.

**Closed by dennishendriksen** 2017-12-08 13:56 UTC
Labels: 5.2, BUG, mod:dataexplorer
