### ISSUE TITLE
Unable to upload test-edgecases.vcf

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4368] opened 2016-01-26 12:13 UTC
the molgenis-annotators/src/test/resources/test-edgecases.vcf gives the following error when trying to import:

org.molgenis.data.MolgenisDataException: Validation error in entity [testEdgecases_Sample]: Invalid characters in: [.] Only letters (a-z, A-Z), digits (0-9), underscores (_) and hashes (#) are allowed.

**Comment by erwinwinder** [comment] 2016-01-26 12:26
Duplicate of https://github.com/molgenis/molgenis/issues/4331 ?

**Comment by Mark-de-Haan** [comment] 2016-01-26 12:35
No I don't think so. This is probably an old vcf test file that was never migrated to work with the newer validation rules or something

**Comment by bartcharbon** [comment] 2016-01-28 11:39
We support uploading VCF's it strike me as "odd" if we need to migrate the actual file...

**Comment by mswertz** [comment] 2016-01-28 21:27
If its wrong format then this is a 'wontfix'?

**Comment by tommydeboer** [comment] 2016-01-29 08:56
Fixed in #4395

**Closed by tommydeboer** 2016-01-29 08:56 UTC
Labels: 1.16.0-RC, bug, molgenis-data-importer, molgenis-data-validation, molgenis-data-vcf, priority-wont-fix
