### ISSUE TITLE
Error creating scatterplot

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#4158] opened 2015-11-17 11:41 UTC
- Load emx_all_datatypes.xls
- Goto dataexplorer and select 'TypeTest'
- Click 'Charts' tab
- Click 'Create scatter plot'
- Select Y axis: 'xdate'
- Select X axis: 'id'

Expected: Scatter plot drawn.
Observed: Message 'Error! An error occured. Please contact the administrator'

Same with boxplot.
Happens when 'id' is selected as X or Y axis.

Stacktrace:
org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query_fetch], all shards failed; shardFailures {[LwIcB3fSQZyNn8MYptwEvQ][molgenis][0]: QueryPhaseExecutionException[[molgenis][0]: query[ConstantScore(cache(+_type:org_molgenis_test_TypeTest +org.elasticsearch.index.search.nested.NonNestedDocsFilter@599674c8))],from[0],size[1000],sort[<custom:"id": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@53972ce6>,<custom:"xdate": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@b6988c>]: Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; } at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:237) at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:183) at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:565) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)

**Comment by fdlk** [comment] 2015-12-08 15:17
Duplicate of the sort on INT ID bug?

**Comment by tommydeboer** [comment] 2015-12-09 14:18
Confirmed that this works in 1.14 now

**Closed by tommydeboer** 2015-12-09 14:18 UTC
Labels: 1.13.0, bug, molgenis-dataexplorer, priority-next
