### ISSUE TITLE
Filter Wizard does not advance to the second page of the wizard when opened for the second time

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2629] opened 2015-03-11 12:59 UTC
In an entity with compound attributes the filter wizard will create multiple pages and while filling in the filter criteria you can advance to the next page by clicking the next button.
When you open the filter wizard for the second time the next button no longer advances you to the next page.

How to reproduce:
- Select an entity with compound attributes
- Click on the filter wizard to set some filter criteria.
- Click on next to go to the next page of the filter wizard
- Click on apply
- Open the filter wizard again
- Click on next

Expected results:
- The filter wizard advances to the next page of the wizard

Actual result
- The filter wizard stays on the first page of the wizard, while the header advances to the next page

This behavior can be observed on the [RD-Connect catalogue test server (Molgenis21)](https://molgenis21.target.rug.nl/menu/main/dataexplorer?entity=rdconnect_Catalogue&hideselect=true&attrs%5B%5D=GUID&attrs%5B%5D=MaterialType&attrs%5B%5D=StorageTemperature&attrs%5B%5D=AnatomicalSite#)

**Comment by Mark-de-Haan** [comment] 2015-03-16 14:36
Fixed and duplicate of #2610

**Closed** 2015-03-16 14:36 UTC
