### ISSUE TITLE
Migration (7->8) fails in rare cases where duplicate packages/groups with different casing exist 

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#9074] opened 2020-08-20 13:07 UTC
### How to Reproduce
create a group "test" in molgenis 7
create a package with name TEST in molgenis 7
migrate to molgenis 8

### Expected behavior
- great succes

### Observed behavior
An error that the TEST_MANAGER role already exists

This is because in molgenis 7 the role names use uppercased group names.
molgenis 8 finds a package "TEST" without a group, so it will create it, and than create the role "TEST_MANAGER", which is identical to the manager role that molgenis 7 created for the "test" group

**Comment by mswertz** [comment] 2020-08-27 07:54
should be clear if we support case-sensitive or not; please choose one and harmonize between these systems.

**Comment by tommydeboer** [comment] 2020-08-27 07:57
The solution to this issue is that the generated group's hash name should be used for the roles. That's how the working of this migration step was intended to avoid collisions, I think missing the role names was an oversight.

**Comment by tommydeboer** [comment] 2020-12-08 13:12
We are opting to close this issue without fixing it because all our servers have been migrated to 8+. 

If you run in to this issue, there's a workaround:
There are `sids` for roles in the `acl_sid` table that you will nog find in the `sys_sec_Role` table. These rows should be deleted (along with any `acl_entry` rows that referenced it).

**Closed by tommydeboer** 2020-12-08 13:12 UTC
Labels: bug, mod:data-migrate
