### ISSUE TITLE
xhyperlink and xhyperlinknillable should not apply URL validation

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3008] opened 2015-05-11 15:01 UTC
To reproduce:
1. Upload the TypeTest test dataset.
2. Create a new row
3. Try to add the value http://localhost:8080 into xhyperlink and xhyperlinknillable.
4. By clicking on the save changes button you will get validation errors

**Comment by dennishendriksen** [comment] 2016-11-28 12:43
Duplicate of #4553

**Closed by dennishendriksen** 2016-11-28 12:43 UTC
Labels: bug, mod:core-ui, mod:data-validation
