### ISSUE TITLE
Model Registry throws an error when I delete an entity from the package

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#3595] opened 2015-09-08 08:50 UTC
When I upload a EMX file and then delete one of the entities including the meta data I will get an error when I try to view the package in the model registry.

## How to reproduce:
1. Upload an EMX file with multiple entities in one package
2. Go to the model registry and verify that the package shows up and can be inspected
3. Delete one of the entities including the metadata
4. Go to the Model registry and select the model from your EMX file

## Expected behaviour:
The model registry will show without errors

## Actual behaviour:
An error is displayed in the model registry and the Tree view does not load. The UML still shows the deleted entity.

**Comment by Mark-de-Haan** [comment] 2015-09-16 08:38
Duplicate of #3157 
Fixed in #3682

**Closed by Mark-de-Haan** 2015-09-16 08:38 UTC
Labels: bug, model-registry, priority: first
