### ISSUE TITLE
Incomprehensible error when a user has no view permissions for an entity used in an R script

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#3644] opened 2015-09-10 13:54 UTC
## To reproduce:
1. Login as a non-super-user
2. Add the following R script in the Scripts plugin (copied from test plan):
   
   ``` r
   library(RCurl)
   eval(expr = parse(
   text = 
   getURL("https://molgenis62.target.rug.nl/molgenis.R?molgenis-token=${molgenisToken}")))
    df <- molgenis.get("Rtest")
    df2 <- apply(df, 1,as.numeric)
    is.na(df2) <- sapply(df2, is.infinite)
    df2[is.na(df2)] <- 0
    df2[is.nan(df2)] <- 0
    png('${outputFile}')
    heatmap(as.matrix(df2),symm=FALSE,trace="none")
    dev.off()
    molgenis.logout()
   ```
   
   Type: **R**
   Generate security token: **Yes**
   Result file extension: **PNG**
3. Upload the Rtest entity (_molgenis-scripts/src/test/resources_)
4. Make sure the user has no permissions for this entity
5. Execute the script
## Expected:

Message pops up telling you that you are not authorised to use this entity in a script.
## Actual:

```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.molgenis.r.MolgenisRException: Error running [/srv/molgenis/.molgenis/omx/data/filestore/sJUtHe5fwm.R].Loading required package: methods
Loading required package: bitops
Error in `is.na<-.default`(`*tmp*`, value = list()) : 
  invalid subscript type 'list'
Calls: is.na<- -> is.na<-.default
Execution halted
```

**Comment by dennishendriksen** [comment] 2015-10-01 05:26
Cannot reproduce. Which permissions did you assign to the non-superuser? Did you generate a token for the non-superuser?

**Comment by tommydeboer** [comment] 2015-11-18 11:59
The user has permissions for the *Script** entities and plugin. I also generated a security token (updated description).

**Comment by Mark-de-Haan** [comment] 2017-11-21 12:56
V5: Scripts are now run inside a Job. The No permission message is located in the logs

**Closed by Mark-de-Haan** 2017-11-21 12:56 UTC
Labels: 1.13.0, bug, mod:r, mod:scripts, priority-next
