### ISSUE TITLE
When I delete the current applied theme an error occures while a warning was expected

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis#6552] opened 2017-08-23 13:30 UTC
### How to Reproduce
Delete the current applied theme via the Data Explorer stylesheet entity

### Expected behavior
A warning was expected with the following content: "Cannot delete the currently selected bootstrap theme"

### Observed behavior
A error occured: "Error! An error occurred. Please contact the administrator."

**Comment by bartcharbon** [comment] 2017-08-24 06:22
Both Mariska and myself cannot reproduce this issue

**Comment by bartcharbon** [comment] 2017-08-24 06:29
The exception with the expected message is thrown, however somewhere it is catched and translated to this general message.

**Comment by bartcharbon** [comment] 2017-08-24 07:47
Discussed with Morris: won't fix for 5.1.0. We might want to add "delete" functionality to the theme manager?

**Comment by Mark-de-Haan** [comment] 2017-11-22 12:11
in v5.3.0-SNAPSHOT, you get the message that you can not delete the currently selected bootstrap theme.

**Closed by Mark-de-Haan** 2017-11-22 12:11 UTC
Labels: 5.1, bug, mod:core-ui
