### ISSUE TITLE
Wizard filter will filter a item out (not in)

### ISSUE THREAD

**Issue by aneashodselmans** [molgenis/molgenis#7673] opened 2018-08-06 14:40 UTC
### How to Reproduce
1) click on entity type test
2) change a email or other item. (for example www.marktplaatst.nl)
3) remember the ID nr.
3) activate the wizard (data item filter) and filter on your changed item
4) you will see that your ID disappeared instead of show only.

**Comment by LuukDijkhuis** [comment] 2018-08-08 07:03
possibly due to the search/index lag. Please check if it's the same if you wait a bit longer. @tommydeboer

**Comment by tommydeboer** [comment] 2018-08-10 09:42
@LuukDijkhuis I couldn't reproduce it. Pretty sure it was index lag. Closing this issue.

**Closed by tommydeboer** 2018-08-10 09:42 UTC
Labels: 7.0.0-RC, bug
