### ISSUE TITLE
SORTA in docker version 8.4.2 has Gateway Time-out for large download files

### ISSUE THREAD

**Issue by mentchf** [molgenis/molgenis#9043] opened 2020-07-03 02:58 UTC
### How to Reproduce
Process a large input file in SORTA docker version 8.4.2 and download the result set.  On my server, a 6000 line output file was successfully downloaded; a 43,000 line output file failed to download.

### Expected behavior
Files successfully processed in SORTA should be downloadable.

### Observed behavior
A 6000-line file downloaded fine.  A 43,000-line file consistently failed giving a "504 Gateway Time-out" error.

![504 gateway time-out](https://user-images.githubusercontent.com/5343244/86426232-28edd880-bcb5-11ea-918c-267016137c7c.jpg)

**Comment by fdlk** [comment] 2020-07-17 12:41
This was an issue with the nginx proxy, fixed in https://github.com/molgenis/docker/pull/76

**Comment by fdlk** [comment] 2020-07-17 12:42
The root cause, the slow download, is filed separately as #9048

**Closed by fdlk** 2020-07-17 12:41 UTC
