### ISSUE TITLE
Editing an entity in the EntityMeta view will break the application

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#2856] opened 2015-04-17 12:20 UTC
## Reproduce
* Go to EntityMeta plugin in the Entities dropdown
* Press the edit button for the ImportRun entity

## Expected
* I can edit the attributes for ImportRun

## Observed
![screen shot 2015-04-17 at 14 20 00](https://cloud.githubusercontent.com/assets/3625016/7201892/e0909ad0-e50c-11e4-8084-4ff7198500b2.png)

**Comment by mswertz** [comment] 2015-04-22 21:27
I suppose only admins face this issue? In that case this is not urgent

**Comment by mswertz** [comment] 2015-05-21 07:58
Cannot reproduce. Probably fixed with new react forms.

**Closed by mswertz** 2015-05-21 07:58 UTC
Labels: bug
