### ISSUE TITLE
Error creating entity with int type ID if you type non-int ID into the form

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3889] opened 2015-10-13 13:22 UTC
Create an entity with int type identity attribute.
Push the +
In the form, type 1:100 into the int attribute input field

Expected:
Validation message warns that field should be an integer

Actual:
Some uniqueness check goes off and alerts with a Big error message with a NumberFormatException.
```
Error! Failed to execute phase [query_fetch], all shards failed; shardFailures {[pY8UYmCzTXyIKBt5md4G6Q][molgenis][0]: QueryPhaseExecutionException[[molgenis][0]: query[filtered(ConstantScore(cache(id:`)))->cache(+_type:RefEntity +org.elasticsearch.index.search.nested.NonNestedDocsFilter@84e62ce2)],from[0],size[25],sort[]: Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; }
```

**Comment by fdlk** [comment] 2015-10-13 13:38
New in 1.11, works fine in 1.10

**Comment by Mark-de-Haan** [comment] 2015-10-14 11:31
I cannot reproduce, Im never allowed to fill in non int characters into an integer field

**Comment by Mark-de-Haan** [comment] 2016-02-13 19:34
I am still not able to edit ID attributes in the data explorer, closing this.

**Closed by Mark-de-Haan** 2016-02-13 19:34 UTC
Labels: 1.11.0, bug, molgenis-forms, priority-first
