### ISSUE TITLE
Correctly configured annotators do not pick up changes in configuration

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#3899] opened 2015-10-14 06:44 UTC
If I have for example a correctly configured snpEff, but I have another snpEff instance I wish to use, the new configuration is only picked up after restart.

**Comment by jjettenn** [comment] 2016-02-22 11:55
Which configuration? Can you be more specific about it?

**Comment by jjettenn** [comment] 2016-02-22 14:07
Cannot reproduce.

**Comment by bartcharbon** [comment] 2016-05-12 12:10
there is only on config item for snpEff, and it is still broken.

1) Correctly cofigured snpEff
2) change config to a exisiting file, but not the snpEff jar

expect:
trouble

actual:
Succesful annotation with the previously configured jar.

The new config is picked up after restart

**Comment by jjettenn** [comment] 2016-07-15 12:57
Fixed in MOLGENIS 2.0

**Closed by jjettenn** 2016-07-15 12:57 UTC
Labels: 1.11.0, 1.21.1, 2.0-RC, bug, molgenis-data-annotators, priority-first
