### ISSUE TITLE
Cascade delete does not work for one to many

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#8447] opened 2019-04-23 06:08 UTC
### How to Reproduce
Create a data model with two entities where entity1 has a xref to entity2 and entity2 a one-to-many to entity1. Set cascade delete on the relationship from entity2 to entity1.
Delete an entity from entity1

### Expected behavior
The delete cascades and deletes the entities from entity2 that are referenced.

### Observed behavior
I get an error that I can't delete the entity because the entity is referenced by entity1

**Comment by dennishendriksen** [comment] 2019-05-06 12:37
@djvanenckevort I'm not sure if I understand the expected behavior.

Suppose you have the following model:
- Book
  - author (xref -> Author)
- Author
  - books (one-to-many mapped by Book.author, cascadeDelete=true)

And you delete a Book. What is the expected behavior? I think that the behavior should be equal to the situation when ```cascadeDelete=false```.

**Comment by fdlk** [comment] 2019-05-14 09:57
@dennishendriksen talked with @djvanenckevort, the point is what happens if you delete the Author. Expected behavior is that the books are deleted as well.

**Comment by dennishendriksen** [comment] 2019-05-20 07:37
FYI [Bidirectional one-to-many cascade remove and orphanRemoval operations](http://www.inanzzz.com/index.php/post/ur2x/bidirectional-one-to-many-cascade-remove-and-orphan-removal-operations-in-doctrine)

**Comment by dennishendriksen** [comment] 2019-05-23 13:23
@djvanenckevort I cannot reproduce your issue:
1. Sign in as superuser
2. Import [it_emx_onetomany.xlsx](https://github.com/molgenis/molgenis/files/3212313/it_emx_onetomany.xlsx) using the import wizard plugin
3. Using the metadata manager plugin enable cascade delete for Author.books
4. Using the data explorer delete an author
The books written by the author are removed as well.

**Comment by djvanenckevort** [comment] 2019-05-27 08:12
Reproducable on 7.x but not on 8.x, issue has been resolved as part of a fix for the deletion of ontologies?

**Comment by mswertz** [comment] 2019-06-11 20:29
can you please and check if we can close this issue for 8.x?

**Comment by djvanenckevort** [comment] 2019-06-12 06:49
see above comment. Has been resolved on 8.x.

**Closed** 2019-08-20 13:54 UTC
Labels: team-platform
