### ISSUE TITLE
When trying to match full search term with double in dataexplorer search quotes an error occurs

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5281] opened 2016-09-23 11:09 UTC
#### Reproduce

<img width="612" alt="screen shot 2016-09-23 at 13 06 35" src="https://cloud.githubusercontent.com/assets/10075439/18783884/c983f5b0-818e-11e6-9bd2-0874dff63c58.png">
#### Expected

Not getting an error (full string match would be nice but not necessary)
#### Observed

<img width="258" alt="screen shot 2016-09-23 at 13 08 40" src="https://cloud.githubusercontent.com/assets/10075439/18783925/fa9e11d0-818e-11e6-8bfe-8c1fc5752548.png">

**Comment by dennishendriksen** [comment] 2016-12-08 09:36
Duplicate of #3865

**Closed by dennishendriksen** 2016-12-08 09:36 UTC
Labels: 1.0.2-BBMRI, 2.0, bug, duplicate, mod:dataexplorer
