### ISSUE TITLE
Broken link in api v3 docs

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis#8873] opened 2020-01-29 14:24 UTC
### How to Reproduce
go to https://molgenis.gitbooks.io/molgenis/content/guide-api-data.html
follow the link in de download section

### Expected behavior
The api spec file is downloaded

### Observed behavior
Nothing happens

**Comment by dennishendriksen** [comment] 2020-01-30 09:41
Duplicate of #8302 (see issue for workaround).

**Closed by dennishendriksen** 2020-01-30 09:41 UTC
Labels: 8.2, bug, documentation
