### ISSUE TITLE
Setting a filter on an mref throws a query shard error

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4807] opened 2016-04-28 15:16 UTC
#### Reproduce
- import this file: 
  [books.xlsx](https://github.com/molgenis/molgenis/files/240815/books.xlsx)
- Go to data explorer and select test_person
- Try to set a filter on book attribute
- Start typing in the mref select field
#### Expected

A drop down with possible mrefs
#### Observed

`Error! Failed to execute phase [query], all shards failed; shardFailures {[pCvh4uM_RiOQGH0ueHKLkA][molgenis][0]: SearchParseException[[molgenis][0]: query[book.ngram:book2],from[0],size[1000]: Parse Failure [Failed to parse source [{"from":0,"size":1000,"query":{"match":{"book.ngram":{"query":"book2","type":"boolean","analyzer":"default"}}},"sort":[{"book.raw":{"order":"asc","mode":"min"}}]}]]]; nested: QueryParsingException[[molgenis] [nested] failed to find nested object under path [book]]; }`

**Comment by fdlk** [comment] 2016-04-28 16:40
Works fine on molgenis01. Is this 2.0 bug?

**Comment by Mark-de-Haan** [comment] 2016-05-09 14:24
No it also happens on molgenis01

**Comment by fdlk** [comment] 2016-05-09 17:08
Worked fine on molgenis01 11 days ago! We've merged #4818 since, could that be the cause?

**Comment by dennishendriksen** [comment] 2016-05-18 09:13
@Mark-de-Haan which version?

**Comment by Mark-de-Haan** [comment] 2016-05-27 09:47
Still in the master version 1.22.0-SNAPSHOT

**Comment by fdlk** [comment] 2017-06-02 16:10
Cannot reproduce in master (4.2-RC)

**Closed by fdlk** 2017-06-02 16:10 UTC
Labels: bug, mod:dataexplorer, priority-first
