### ISSUE TITLE
When adding "No match" to a term in SORTA, in the output "Malignant neoplasm: Parathyroid gland" is returned

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5285] opened 2016-09-26 09:38 UTC
#### Reproduce

Add a term (like MS) to sorta and use the ICD10 ontology
<img width="867" alt="screen shot 2016-09-26 at 11 31 34" src="https://cloud.githubusercontent.com/assets/10075439/18829599/4b812092-83dd-11e6-9a59-3ca00dbe280b.png">
No match is correct, so i select "no match"
<img width="1257" alt="screen shot 2016-09-26 at 11 32 23" src="https://cloud.githubusercontent.com/assets/10075439/18829617/62dcc0c0-83dd-11e6-9906-8fe095eb882b.png">
<img width="1265" alt="screen shot 2016-09-26 at 11 32 36" src="https://cloud.githubusercontent.com/assets/10075439/18829616/62db5a0a-83dd-11e6-95fb-0e454ebf207b.png">
Its in the results 
<img width="1264" alt="screen shot 2016-09-26 at 11 32 48" src="https://cloud.githubusercontent.com/assets/10075439/18829615/62da7cac-83dd-11e6-8935-5d7d2c8b56b2.png">
But when i download...
![screen shot 2016-09-26 at 11 34 28](https://cloud.githubusercontent.com/assets/10075439/18829618/62ddffbc-83dd-11e6-847d-4006b173b59c.png)
#### Expected

I expect to get no value or NA
#### Observed

I get malignant neoplasm...

**Comment by dennishendriksen** [comment] 2017-11-03 07:21
Duplicate of #4929

**Closed by dennishendriksen** 2017-11-03 07:21 UTC
Labels: 1.21.4, bug, mod:data-mapper, priority-first
