### ISSUE TITLE
Footer overlaps mapping service buttons if GA is enabled

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6611] opened 2017-09-08 07:41 UTC
### How to Reproduce
- Enable GA in the settings
- Create a mapping project
- Create a mapping
- Try click on the button to run the mapping

### Expected behavior
I can click the button

### Observed behavior
I can't click the button, GA text is on top of the button.

**Comment by tommydeboer** [comment] 2017-09-18 11:17
@mswertz @djvanenckevort @marikaris Is a fix needed in the 5.2 release? 

(btw: The problem also arises at the download button in the Data Explorer and potentially numerous other places, depending on the length of the custom footer text)

**Comment by tommydeboer** [comment] 2017-09-19 09:08
The above PR fixes the 'unclickability' of buttons/links at the bottom of the page, but introduces the problem that the footer runs off the page and you need to scroll down to see the whole thing. Therefore I'm keeping this issue open.

**Comment by Mark-de-Haan** [comment] 2017-11-22 12:28
Closing this, as the issue is fixed.

Needing to scroll to see complete footer content if the content is 6-10 paragrahps of text does not sound like a bug.

**Closed by Mark-de-Haan** 2017-11-22 12:28 UTC
Labels: 5.1, bug, mod:core-ui
