### ISSUE TITLE
adding a value in the xmref select box does not select this value

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4635] opened 2016-03-08 13:06 UTC
reproduce:
- open any form containing an x or mref
- click the plus in the dropdown to add a value

expected:
the added value is created and selected in the dropdown

actual:
the value is added, however it is not selected in the dropdown.

**Comment by dennishendriksen** [comment] 2016-12-02 07:58
Duplicate of #5027, closing this issue since the other issue description provides more information.

**Closed by dennishendriksen** 2016-12-02 07:58 UTC
Labels: 1.18.0, 2.0-RC, bug, mod:forms
