### ISSUE TITLE
When using the REST api v2 to update data I get an internal server error

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5926] opened 2017-03-13 11:10 UTC
### How to Reproduce
Load data of BBMRI nl 
Mail Mariska for queries done on data and use these

### Expected behavior
Data gets updated, no error occurs

### Observed behavior
Data gets updated, but internal server error is also shown

**Comment by dennishendriksen** [comment] 2017-03-22 07:53
The REST queries provided by Mariska and the resulting errors are probably caused by #5891 which is fixed in MOLGENIS 3.0.

**Closed by dennishendriksen** 2017-03-22 07:53 UTC
Labels: 2.0, bug, mod:data-rest
