### ISSUE TITLE
In EMX importer I get: 'Missing idAttribute for entity ...' when you get the entities + packages + fully qualified name wrong

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#5203] opened 2016-08-17 14:40 UTC
#### Reproduce

Data is private, ask Marieke if needed.
#### Expected

Import success.
#### Observed

Missing idAttribute for entity ...

*Work-around: Put all entities in backend ElasticSearch.

**Comment by dennishendriksen** [comment] 2016-08-17 17:24
Imports without any issues in MOLGENIS 2.0-RC

**Comment by bartcharbon** [comment] 2016-08-29 13:20
to be investigated in 2.0... the problem was that the data was not using the fully qualified name in the excel (attrbutes sheet, entitynames in tabs). So in fact it is strange that it works in 2.0

**Comment by Mark-de-Haan** [comment] 2016-10-27 11:15
How is *missing ID attribute for entity x* a weird error message?

**Comment by dennishendriksen** [comment] 2016-11-07 08:50
@marieke-bijlsma can you reproduce the issue yourself using the molgenis/master branch code? If the answer is no, I propose you close this issue. If the answer is yes, could you please email me with the data or information on how to retrieve the data to reproduce this issue?

**Comment by dennishendriksen** [comment] 2016-11-07 10:03
@marieke-bijlsma will ook into it in Sprint 94

**Comment by fdlk** [comment] 2016-11-17 07:55
Taken a look with @marieke-bijlsma . If you specify the package of an entity in the entities sheet, you have to refer to it by its fully qualified name in the attributes sheet. If you do not, the attributes are assumed to belong to a different entity and the one mentioned in the entities sheet has no attributes at all, not even an id attribute.

**Comment by fdlk** [comment] 2016-11-17 07:57
The user-friendly thing to do would be to add a message if an EMX entity has no attributes at all and another entity exists with the same name.

**Closed** 2017-04-12 07:57 UTC
Labels: 2.0, enhancement, mod:data-importer
