### ISSUE TITLE
Order of the attributes is not consistent in the data explorer

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2772] opened 2015-04-09 08:40 UTC
The order of the attributes is not consistent in the data explorer. Compare molgenis14 to molgenis35. Both have the same data model and neither has the attributes in the same order as in the EMX file.
![schermafbeelding 2015-04-09 om 10 38 17](https://cloud.githubusercontent.com/assets/1942445/7063157/96c23e5e-dea4-11e4-8d4e-d371021d2bc8.png)
![schermafbeelding 2015-04-09 om 10 38 24](https://cloud.githubusercontent.com/assets/1942445/7063158/96e5c310-dea4-11e4-9c1e-b289a3a95119.png)

EMX file in GCC Dropbox Projects/BBMRI Catalogue 2.0/bbmri-nl-final.xlsx

**Comment by Mark-de-Haan** [comment] 2015-04-09 12:33
If I remember correctly, this was fixed in the 1.5.0 release..

**Comment by fdlk** [comment] 2015-04-09 16:52
Duplicate of #2582 I think, yes.

The order is preserved by the elasticsearch repository, but if for some reason the repository got dropped or reindexed, then there is no way to restore it.

**Closed** 2015-04-09 16:53 UTC
Labels: bug, dataexplorer
