### ISSUE TITLE
As user I want to run Magma scripts in the script module

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis#8043] opened 2018-12-05 13:55 UTC
### How to Reproduce
Try to run test-case: SCRIPTSYS002 from the scripts test plan

### Expected behavior
Result == 23.148148148148145

### Observed behavior
Result ==
14:54:56.659 - Execution started.
14:54:56.692 - Failed. null

**Comment by dennishendriksen** [comment] 2018-12-06 07:38
@sidohaakma duplicate of #7607 for which a work in progress fix exists in PR #7608?

**Closed** 2018-12-06 10:30 UTC
Labels: 7.2, 7.3.5, bug, mod:scripts
