### ISSUE TITLE
If session times out during import, the importer logs that as cause for import failure

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3109] opened 2015-05-29 07:58 UTC
Fortunately it does not roll back the import.

```
INFO: Server startup in 49167 ms
14:39:27.956 [pool-6-thread-1] INFO  org.molgenis.data.importer.ImportJob - Import started
19:13:21.081 [pool-6-thread-1] INFO  org.molgenis.data.importer.ImportJob - Import failed.
java.lang.IllegalStateException: setAttribute: Session [041558ACB8DFCB524FFFAA4E6ED5E669] has already been invalidated
	at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1437) ~[catalina.jar:7.0.37]
	at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1402) ~[catalina.jar:7.0.37]
	at org.apache.catalina.session.StandardSessionFacade.setAttribute(StandardSessionFacade.java:156) ~[catalina.jar:7.0.37]
	at org.molgenis.data.importer.ImportJob.run(ImportJob.java:61) ~[molgenis-data-import-1.6.0.jar:1.6.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by mswertz** [comment] 2015-05-30 18:11
What is expected behavior: if a user logs in again after timeout then user finds the import completed (or failed because right reasons).

**Comment by fdlk** [comment] 2015-05-30 18:27
That's tricky since we store the state of the import job wizard in the user's session. (See #2825)

**Comment by mswertz** [comment] 2015-05-30 20:02
suggests this would then become a new feature request :-)


On Sat, May 30, 2015 at 8:27 PM, Fleur Kelpin <notifications@github.com>
wrote:

> That's tricky since we store the state of the import job wizard in the
> user's session. (See #2825
> <https://github.com/molgenis/molgenis/issues/2825>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3109#issuecomment-107074193>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by fdlk** [comment] 2015-05-31 15:04
I'd expect the log to properly state the result or failure, regardless of the existence of the user session.

**Comment by mswertz** [comment] 2015-05-31 15:05
agreed. That is the bugfix needed before we can close this issue I suppose.

On Sun, May 31, 2015 at 5:04 PM, Fleur Kelpin <notifications@github.com>
wrote:

> I'd expect the log to properly state the result or failure, regardless of
> the existence of the user session.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3109#issuecomment-107202207>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Closed** 2015-06-10 07:57 UTC
Labels: bug, data-importer, priority: first
