### ISSUE TITLE
Entity reports (module) no longer work

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4371] opened 2016-01-26 14:04 UTC
## Reproduce
* For the data explorer settings, set the Reports to "ImportRun:test,MolgenisUser:test2"
* Create two freemarker templates
** Name : view-test-entitiesreport.ftl
** Value : test

** Name : view-test2-entitiesreport.ftl
** Value : test2

* Navigate to the ImportRun entity and click the test module tab

## Expected
I see the word test

## Observed
```
14:59:42.162 [ajp-bio-8009-exec-17] ERROR freemarker.runtime - Error executing FreeMarker template
freemarker.core._MiscTemplateException: Template inclusion failed (for parameter value "view-test2-entitiesreport.ftl"):
Template not found for name "view-test2-entitiesreport.ftl".
The name was interpreted by this TemplateLoader: MultiTemplateLoader(loader1 = org.springframework.ui.freemarker.SpringTemplateLoader@18da7c89, loader2 = ClassTemplateLoader(resourceLoaderClass=org.springframework.web.servlet.view.freemarker.FreeMarkerConfigurer, basePackagePath="" /* relatively to resourceLoaderClass pkg */)).
```

```
Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "view-test2-entitiesreport.ftl".
The name was interpreted by this TemplateLoader: MultiTemplateLoader(loader1 = org.springframework.ui.freemarker.SpringTemplateLoader@18da7c89, loader2 = ClassTemplateLoader(resourceLoaderClass=org.springframework.web.servlet.view.freemarker.FreeMarkerConfigurer, basePackagePath="" /* relatively to resourceLoaderClass pkg */)).
	at freemarker.template.Configuration.getTemplate(Configuration.java:1833) ~[freemarker-2.3.23.jar:2.3.23]
	at freemarker.core.Environment.getTemplateForInclusion(Environment.java:2044) [freemarker-2.3.23.jar:2.3.23]
	at freemarker.core.Include.accept(Include.java:158) ~[freemarker-2.3.23.jar:2.3.23]
	... 111 common frames omitted
```

**Comment by erwinwinder** [comment] 2016-01-26 14:40
Duplicate of https://github.com/molgenis/molgenis/issues/4370

**Closed by erwinwinder** 2016-01-26 14:40 UTC
Labels: 1.16.0-RC, bug, molgenis-dataexplorer
