### ISSUE TITLE
Deleting a dataset removes the elastic search mapping, but not the actual stored documents

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4812] opened 2016-04-29 09:38 UTC
Selenium test server (31) ran out of disk space. 
Manually deleting the index folder opened up 7G of space.

This server is subjected to file imports + deletes multiple times per hour.

**Comment by fdlk** [comment] 2016-05-03 08:59
Duplicate of #4776 ?

**Comment by Mark-de-Haan** [comment] 2016-05-03 09:01
Hmm That issue was not fixed properly?

**Comment by fdlk** [comment] 2016-05-03 09:05
Sounds good to me.

**Comment by Mark-de-Haan** [comment] 2016-05-09 14:32
Closed together with  #4776

**Closed** 2016-05-09 14:32 UTC
Labels: bug-unclear, found-by-selenium, molgenis-data-elasticsearch

**Comment by dennishendriksen** [comment] 2016-05-18 09:10
@Mark-de-Haan Which version contains the problem/fix?
