### ISSUE TITLE
Adding new xref/mref items from "old forms" numbers typed sometimes 'get eaten'.

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis#8889] opened 2020-02-05 09:23 UTC
### How to Reproduce
Create new xref or mref with plus sign from "old forms". Type in number to be new xref or mref item.

### Expected behavior
When window for new xref/mref is vissible, that typing 6 numbers can be done without problems.

### Observed behavior

While typing sometimes numbers 'get eaten'. Added gif, to show what happens.
![verdwijnende_cijfers](https://user-images.githubusercontent.com/40240913/73828469-9595a180-4801-11ea-8287-da0697c83673.gif)

**Comment by bartcharbon** [comment] 2020-02-05 10:45
duplicate of https://github.com/molgenis/molgenis-frontend/issues/254

@dennishendriksen the old forms are in the molgenis repo right? so that issue should not have been moved to the frontend repo?

**Closed** 2020-02-05 10:48 UTC
Labels: 8.2, bug
