### ISSUE TITLE
When editing a value in TypeTest, a MolgenisDataException occurs 

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#5426] opened 2016-10-31 11:14 UTC
#### Reproduce
1. Import [emx_5426.xlsx](https://github.com/molgenis/molgenis/files/563736/emx_5426.xlsx)
2. Go to the data explorer and select the TestIntId entity
3. Edit a row and change label to test1234
4. Press save
5. Now google search for test1234

(note that the same works for the TestStringId entity)

#### Expected
After waiting for the index, I find the row I just edited

#### Observed
No row is found, logging shows:
```
Caused by: org.molgenis.data.MolgenisDataException: Attribute [id] query value is of type [String] instead of [Integer]
	at org.molgenis.data.postgresql.PostgreSqlUtils.getPostgreSqlQueryValue(PostgreSqlUtils.java:194) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.postgresql.PostgreSqlQueryGenerator.getSqlWhere(PostgreSqlQueryGenerator.java:766) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.postgresql.PostgreSqlQueryGenerator.getSqlSelect(PostgreSqlQueryGenerator.java:449) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.postgresql.PostgreSqlRepository$1.getBatch(PostgreSqlRepository.java:430) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.support.BatchingQueryResult.getBatch(BatchingQueryResult.java:36) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.support.BatchingQueryResult.getBatch(BatchingQueryResult.java:14) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.util.BatchingIterable$1.nextBatch(BatchingIterable.java:138) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.util.BatchingIterable$1.hasNext(BatchingIterable.java:58) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811) ~[na:1.8.0_71]
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[na:1.8.0_71]
	at org.molgenis.data.postgresql.PostgreSqlRepository.findOne(PostgreSqlRepository.java:165) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.postgresql.PostgreSqlRepository.findOneById(PostgreSqlRepository.java:179) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.cache.l2.L2Cache$1.load(L2Cache.java:186) ~[molgenis-data-cache-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.cache.l2.L2Cache$1.load(L2Cache.java:177) ~[molgenis-data-cache-2.0.0-SNAPSHOT.jar:na]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542) ~[guava-19.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323) ~[guava-19.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286) ~[guava-19.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[guava-19.0.jar:na]
	... 31 common frames omitted
```

**Comment by fdlk** [comment] 2016-10-31 20:27
Duplicate of #4213 perhaps?

**Closed** 2016-11-03 13:42 UTC
Labels: 2.0-RC, bug, molgenis-dataexplorer
