### ISSUE TITLE
On pressing previous/next in browser, error shows in data explorer

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#4314] opened 2016-01-08 09:23 UTC
When loading a table, then another and pushing previous or next (it does not always happen, but regularly) in the browser (happens by mistake when the mousepad, very annoying), an error occurs. 
This error is produced using chrome.
![screen shot 2016-01-08 at 10 20 28](https://cloud.githubusercontent.com/assets/10075439/12194646/d7446b4e-b5f1-11e5-9561-2769e23b7aa4.png)

**Comment by mswertz** [comment] 2016-01-28 21:46
Can it be easily reproduced (and how to do that)?

**Comment by marikaris** [comment] 2016-01-29 07:25
Yes, I just reproduced it, I used the tables of the chromosome 6 questionnaire, I can't reproduce it with small tables (like the phenotype tables of the chromosome 6 questionnaire), I don't have other large tables to check it with. 
Selecting first one table (questionnaire part A_C) in the dataexplorer, then another (questionnaire D_H) and then a third (questionnaire I_L), and pushing previous and next button after that is the easiest way to reproduce, since the error does not occur always.

**Comment by marikaris** [comment] 2017-02-02 07:36
Cannot be reproduced in firefox

**Comment by dennishendriksen** [comment] 2017-09-25 14:18
Duplicate of #6704

**Closed by dennishendriksen** 2017-09-25 14:18 UTC
Labels: 1.21.4, 2.0, 3.0, bug, duplicate, mod:dataexplorer, priority-someday
