### ISSUE TITLE
Mapping Service gives error when making/opening a project

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#2932] opened 2015-04-28 13:14 UTC
### To reproduce:
1. Open the Mapping Service
2. Create a new project

### Expected:
Project overview will be shown.

### Actual:
New page is opened with: ```{"errors":[{"message":"An error occurred. Please contact the administrator.<br />Message:null"}]}```

**Comment by dennishendriksen** [comment] 2015-04-29 12:37
Cannot reproduce.

**Comment by tommydeboer** [comment] 2015-05-04 07:47
Can reproduce again: use *tags*, *entities* or *attributes* as target entity when creating a new project.

**Comment by mswertz** [comment] 2015-05-20 20:48
wontfix if this only relates to metadata tables

**Closed** 2015-05-21 08:07 UTC
Labels: bug, release test v15.05, wontfix
