### ISSUE TITLE
Saving changed in edit form gives Unspecified error.

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3898] opened 2015-10-14 06:40 UTC
Reproduce:
- Import molgenis-app\src\test\resources\xls\emx_all_datatypes.xlsx
- Open TypeTest in data explorer
- Select edit icon on row with id 1
- Press Save changes in form

Expected:
- Success message

Actual:
- ```Error! An error occurred. Please contact the administrator.
Unspecified error.```

**Comment by erwinwinder** [comment] 2015-10-14 09:06
Cannot reproduce this

**Comment by tommydeboer** [comment] 2015-10-14 11:40
Confirmed irreproducible by reporter. Will close this issue.

**Closed by tommydeboer** 2015-10-14 11:40 UTC
Labels: 1.11.0-RC, bug-normal, molgenis-dataexplorer
