### ISSUE TITLE
Internal Server Error when creating a new "integrated dataset" with the name: "TargetRepo"

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4382] opened 2016-01-27 15:36 UTC
Download from this page:	https://goo.gl/cfdzDL
Upload HOP-10-attributes.xls	
Upload lifelines-emx-demo.xls	
Upload prevend-emx-demo.xls	
"Create a new mapping project:
- target: HOP"	
"Add sources to the project:
- lifelines
- prevend"	
"Create integrated dataset:
- name: TargetRepo"	

Expected:
New entity "TargetRepo" is created

Result:
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, root@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log.
Apache/2.2.15 (CentOS) Server at molgenis62.target.rug.nl Port 443

**Comment by Mark-de-Haan** [comment] 2016-01-28 08:48
Duplicate of #3630

**Closed by Mark-de-Haan** 2016-01-28 08:48 UTC
Labels: 1.16.0-RC, bug, molgenis-data-mapper
