### ISSUE TITLE
Test Questionnaire EMX file is not properly localized

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#7558] opened 2018-07-16 13:55 UTC
### How to Reproduce
- As superuser navigate to the 'Data explorer' plugin, select entity 'Language', select 'edit' icon for row 'Deutsch', set 'active' to true, select 'Save changes'
- Select 'Deutch' in menu header dropdown
- As superuser import [emx-questionnaire.xlsx](https://github.com/molgenis/molgenis/files/2197842/emx-questionnaire.xlsx) from `molgenis-questionnaires\src\test\resources\emx-questionnaire.xls` in Chrome 67.0.3396.99
- Navigate to the 'Questionnaires' plugin in menu 'Plugins'
- Select 'View Questionnaire' for questionnaire 'Test questionnaire'
- Select 'Start questionnaire'

### Expected behavior
- Answer options are localized

### Observed behavior
- Answer options are in English

**Comment by bartcharbon** [comment] 2018-07-17 12:42
This sounds a lot like #7437 which has been fixed by https://github.com/molgenis/molgenis/pull/7491

**Comment by bartcharbon** [comment] 2018-07-17 12:52
The issue is in the fact that "label-en" seems to be the default label, therefore for the german translation the app searches for "label-en-de" which cannot be found and the app falls back to the default.

test data should be fixed

**Closed** 2018-07-17 14:04 UTC
Labels: 7.0.0-RC, bug, mod:questionnaires
