### ISSUE TITLE
Manual adding and removing tag in tagging service is not working.

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4380] opened 2016-01-27 12:41 UTC
## Reproduce

Download the folder (real_examples) at: https://drive.google.com/drive/folders/0B7qHi41THTs_T3BnaHY2TGJ1Mzg
"Demo target data and source data 
1. mappingservice-test.xlsx" Upload via the upload page 
"Demo ontology files:
2. biobank_ontology.owl.zip
3. uo.owl.zip" Upload via the upload page
"Demo magma script type and algorithm template file:
4. test-javascript_magam.xls" Upload via the upload page

Go to the "Tag Wizard"
Select an entity to tag: HOP_selenium
Select an ontology: biobank_ontology; uo;
add manually the tag "Weight" to attribute "Body_Mass_Index_1"
remove the tag "Weight".

Go to the "Mapping Service"
Add the a new mapping project with HOP_selenium as target.
### Expected:

No tagging Weight exists
### Result:

Tagging "Weight" exists

**Comment by mswertz** [comment] 2016-01-28 21:23
@ChaoPang is this desired behavior? I mean, I though we stopped the manual tagging!!!

**Comment by fdlk** [comment] 2016-04-05 12:44
I think it would definitely be a bug if the tags you remove in the tag wizard still show in the mapping service. But I cannot reproduce.

**Comment by Mark-de-Haan** [comment] 2017-07-10 09:08
Fixed in v5.0.0

**Closed by Mark-de-Haan** 2017-07-10 09:08 UTC
Labels: 1.15.0, 1.16.0, 1.19.0, bug, mod:data-mapper, priority-someday
