### ISSUE TITLE
Error sorting on id column

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#4157] opened 2015-11-17 10:21 UTC
- Upload emx_all_data_types.xls
- Goto the dataexplorer and select 'TypeTest'
- Sort on (click)  'id' column

Expected: Data sorted on id
Observed:

![screen shot 2015-11-17 at 11 19 16](https://cloud.githubusercontent.com/assets/116559/11208773/53163f8e-8d1d-11e5-8908-b763a573c43a.png)

**Comment by bartcharbon** [comment] 2015-11-19 09:19
duplicate of #2754?

**Closed** 2015-11-19 09:27 UTC
Labels: 1.13.0-RC, bug, molgenis-dataexplorer, priority-first
