### ISSUE TITLE
Import wizard occasionally hangs on fast-failing import jobs

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6595] opened 2017-09-06 11:21 UTC
### How to Reproduce
- Download an existing entity with the downloader
- Update some records and add a few new ones
- Upload the entity and choose 'Update'

### Expected behavior
- Upload should fail saying that there were new entities found

### Observed behavior
- Upload hangs, spinner keeps rotating and Finished button is grayed out

Tested on MOLGENIS 5.1

**Comment by dennishendriksen** [comment] 2017-09-06 13:50
Cannot reproduce using the following steps:
1. Import `molgenis-platform-integration-tests\src\test\resources\xls\it_emx_datatypes.xlsx`
2. Add a row to worksheet `it_emx_datatypes_TypeTestRef` with: ref6 label6
3. Import the updated xlsx
Result: ```Cannot update [it_emx_datatypes_TypeTestRef] with id [ref6] because it does not exist```

Can you provide both the initial and the updated data sets?

**Comment by djvanenckevort** [comment] 2017-09-06 13:59
Send the dataset in question by mail.

**Comment by dennishendriksen** [comment] 2017-09-07 10:48
We managed to reproduce the issue by modifying ```org.molgenis.data.importer.wizard.ValidationResultWizardPage```:
```java
public String handleRequest(HttpServletRequest request, BindingResult result, Wizard wizard) 
{
   ...
   asyncImportJobs.execute(...)
   ...
}
```
```java
public String handleRequest(HttpServletRequest request, BindingResult result, Wizard wizard) 
{
   ...
   asyncImportJobs.execute(...)
   try
   {
     Thread.sleep(10000L);
   }
   catch (InterruptedException e) {}
   ...
}
```
and importing/updating the dataset that was provided by mail.

**Comment by dennishendriksen** [comment] 2017-09-07 10:52
Cause of the issue is the Transactional annotation of handleRequest:
1. The import run entity is added in the transaction on the main thread
2. The import job is executed async on another thread
3. An exception occurs in the import job thread resulting in an update of the import run entity status
4. The import run does not exist in the import job thread transaction, because the main thread transaction hasn't been committed yet

**Closed** 2017-09-07 21:26 UTC
Labels: bug, mod:data-importer
