### ISSUE TITLE
Various errors when blocking third-party cookies

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6060] opened 2017-04-18 13:37 UTC
### How to Reproduce
1. Block third-party cookies and site data (in Chrome: Settings > Advanced > Privacy > Content Settings...
2. Go to MOLGENIS

### Expected behavior
Site works as intended. If Google Analytics is turned on, user should not be tracked and not receive any warnings.

### Observed behavior
Every page shows an error:

```
Error! An error occurred. Please contact the administrator.
Script error.
```

And the Log out button doesn't work.

**Comment by dennishendriksen** [comment] 2017-04-19 12:34
Duplicate of #5869

**Closed by dennishendriksen** 2017-04-19 12:34 UTC
Labels: 3.0, 4.0-RC, bug
