### ISSUE TITLE
Metadata editor does not allow updating valid entity, when id attribute is changed 

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#6794] opened 2017-10-07 07:54 UTC
### How to Reproduce
- Create a entity ( using metadataeditor), press save to persist the entity.
- Update the entity by adding a new attribute, make this new attribute unique and non nullable, make this new attribute the id attribute, update the old id attribute by making it non-unique and nullable.
- save the changes.
### Expected behavior
The updated entity is stored.

### Observed behavior
A error is show ' can not update entity, id attribute can not be nullable' , and the entity is not updated.

**Comment by ConnorStroomberg** [comment] 2017-10-07 07:56
Workaround: Split updating the entity into 2 steps ( create new attribute, and change the id attribute). Persist between steps.

**Comment by dennishendriksen** [comment] 2017-10-13 11:02
@ConnorStroomberg which version(s) are affected? can you add the relevant version label(s)?

**Comment by mswertz** [comment] 2018-06-23 12:23
we aim to discontinue user defined ID so that should overcome this issue

**Comment by dennishendriksen** [comment] 2018-09-10 05:38
Duplicate of #6928

**Closed by dennishendriksen** 2018-09-10 05:38 UTC
Labels: 5.2, bug, master, mod:metadata-manager
