### ISSUE TITLE
entering an invalid hyperlink does not result in a validation failure

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#5868] opened 2017-03-01 10:10 UTC
### How to Reproduce
edit a row in typetest
enter "qwerty" in the xhyperlink field 

### Expected behavior
validation message that this is not a hyperlink

### Observed behavior
no message, for saves fine

**Comment by dennishendriksen** [comment] 2017-03-01 11:30
Duplicate of #5531

**Closed** 2017-03-01 12:28 UTC
Labels: 3.0-RC, bug, mod:forms
