### ISSUE TITLE
Algorithm in Mapping Service is not refreshed

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4381] opened 2016-01-27 14:12 UTC
## Reproduce
Download the folder (real_examples) at: https://drive.google.com/drive/folders/0B7qHi41THTs_T3BnaHY2TGJ1Mzg
"Demo target data and source data 
1. mappingservice-test.xlsx" Upload via the upload page 
"Demo ontology files:
2. biobank_ontology.owl.zip
3. uo.owl.zip" Upload via the upload page
"Demo magma script type and algorithm template file:
4. test-javascript_magam.xls" Upload via the upload page

Go to the "Tag Wizard"
Select an entity to tag: HOP_selenium
Select an ontology: biobank_ontology; uo;
add manually the tag "Weight" and "Height" to attribute "Body_Mass_Index_1"

Go to the "Mapping Service"
Add a new mapping project with HOP_selenium as target.
Add source "lifelines_test"
Click in pencil of "Body Mass Index kg/m^2 (decimal)" to edit.
Algorithm is correctly shown.
[HEIGHT_2] and [WEIGHT] are selected as expected.
Search on Height

###Expected:
The algorithm is changed to: $('HEIGHT_2').unit('cm').value();

###Result: 
Three attributes: HEIGHT_2; HEIGHT; HEIGHT_1; are shown.
Algorithm is not changed.

**Comment by Mark-de-Haan** [comment] 2016-01-28 09:44
You expect the algorithm to change by searching? I do not understand. If I search for height and I select one of the three, that one will be inserted into the algorithm area. I do not see whats wrong with this behavior.

**Comment by jjettenn** [comment] 2016-01-28 12:42
The state of the page is not updated.
So after searching an attribute is removed and the algorithm is not updated.

**Comment by Mark-de-Haan** [comment] 2016-01-28 12:48
The table always contains the checkboxes, they are just hidden with some css. So they are still selected, just not visible

**Comment by mswertz** [comment] 2016-01-28 21:21
It is unclear to me if this is really a bug, and even if it is it seems not new 
What does @ChaoPang think?

**Comment by tommydeboer** [comment] 2016-01-29 07:45
I also wouldn't expect the algorithm to change when you search for another attribute. Wouldn't that mean that you can never add more than one attribute, because you remove the first one every time you search for another?

**Comment by jjettenn** [comment] 2016-01-29 08:18
The problem is that we have combined the selection of the attributes with the search function.
It should be separated.

**Comment by jjettenn** [comment] 2016-01-29 08:19
Your selection should stay on the page when searching.

**Comment by tommydeboer** [comment] 2016-02-01 11:17
Then I'd say this is a feature request to always have the selected attributes be visible? In the current version you can still see the selected attributes if you empty your search bar, btw.

**Comment by fdlk** [comment] 2016-02-01 12:06
Not a bug, but a feature request.

**Closed by fdlk** 2016-02-01 12:06 UTC
Labels: 1.15.0, 1.16.0-RC, bug, bug-unclear, molgenis-data-mapper
