### ISSUE TITLE
Add language gives wrong error

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis#8664] opened 2019-09-17 10:22 UTC
### How to Reproduce
During release test: I18N001
Try to add a new language

### Expected behavior
You will get the error message: "exclamation-sign Language could not be created. Adding languages is not allowed"

### Observed behavior
I got a message: "An error has occurred."

**Comment by fdlk** [comment] 2019-10-25 19:44
Duplicate of #8351

**Closed by fdlk** 2019-10-25 19:44 UTC
Labels: 8.2-RC
