### ISSUE TITLE
Detecting file extension in generic importer is wrong

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#2529] opened 2015-02-25 10:09 UTC
OptionsWizardPage.java
Line 61: 		if (importWizard.getMustChangeEntityName())

// TODO FIXME wrong way to decide the extension of the file. It will not detect, for example a file with
				// the obo.zip extension.

We should decide how we are going to detect to the extensions

**Comment by mswertz** [comment] 2015-05-21 06:34
what is now problem with user experience?

**Comment by bartcharbon** [comment] 2015-06-19 11:22
The problem is that the files with a "double" extension will not upload, for e.g. vcf.gz

We do not need to decide anything, there is already a perfectly fine utilty function for this that was implemented for other parts of the importer.

**Comment by bartcharbon** [comment] 2015-06-19 11:49
fixed on my annotator branch: feature/3495

**Closed** 2016-02-12 12:48 UTC
Labels: bug, molgenis-data-importer, priority-next
