### ISSUE TITLE
Cannot update entity with file attribute

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#6061] opened 2017-04-18 13:38 UTC
### How to Reproduce
* Upload 
[file_datatype-test.xlsx](https://github.com/molgenis/molgenis/files/929806/file_datatype-test.xlsx).
* Create an entity of type File, with a value for the Attachment attribute
* Edit the entity
* In the form, update the value for description

### Expected behavior
The form shows the file name

### Observed behavior
Chrome:
> Uncaught InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.

Safari:
> InvalidStateError (DOM Exception 11): The object is in an invalid state.

**Comment by dennishendriksen** [comment] 2017-04-19 12:31
Duplicate of #5532

**Closed by dennishendriksen** 2017-04-19 12:31 UTC
Labels: 3.0, 4.0-RC, bug, mod:forms
