### ISSUE TITLE
Cmdline annotator in update mode writes bad values

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis#5039] opened 2016-07-12 07:53 UTC
Running an annotator in update mode a variant, but no hits were found, results in this:

```
1       886817  rs111748052     C       T,CATTTT    CADD=0.199589,.;CADD_SCALED=4.675,.;
```

Being written out as:

```
1       886817  rs111748052     C       T,CATTTT    CADD=0.199589,;CADD_SCALED=4.675,;
```

Note that the empty value '.' is now gone. Subsequent annotators will then fail with

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at org.molgenis.data.annotation.filter.MultiAllelicResultFilter.filter(MultiAllelicResultFilter.java:151)
        at org.molgenis.data.annotation.filter.MultiAllelicResultFilter.filterResults(MultiAllelicResultFilter.java:109)
        at org.molgenis.data.annotation.entity.impl.AnnotatorImpl.processQueryResults(AnnotatorImpl.java:37)
        at org.molgenis.data.annotation.entity.impl.QueryAnnotatorImpl.annotateEntity(QueryAnnotatorImpl.java:106)
        at org.molgenis.data.annotation.entity.impl.QueryAnnotatorImpl.annotateEntity(QueryAnnotatorImpl.java:32)
        at org.molgenis.data.annotation.entity.impl.RepositoryAnnotatorImpl.annotateEntity(RepositoryAnnotatorImpl.java:53)
        at org.molgenis.data.annotation.AbstractRepositoryEntityAnnotator$1.next(AbstractRepositoryEntityAnnotator.java:51)
        at org.molgenis.data.annotation.AbstractRepositoryEntityAnnotator$1.next(AbstractRepositoryEntityAnnotator.java:28)
        at org.molgenis.data.annotation.cmd.CmdLineAnnotator.annotate(CmdLineAnnotator.java:320)
        at org.molgenis.data.annotation.cmd.CmdLineAnnotator.annotate(CmdLineAnnotator.java:227)
        at org.molgenis.data.annotation.cmd.CmdLineAnnotator.run(CmdLineAnnotator.java:154)
        at org.molgenis.data.annotation.cmd.CmdLineAnnotator.main(CmdLineAnnotator.java:177)
```

**Comment by dennishendriksen** [comment] 2017-03-24 12:19
Duplicate of #5329

**Closed by dennishendriksen** 2017-03-24 12:19 UTC
Labels: 1.21.1, bug, mod:data-annotators, mod:data-vcf
