### ISSUE TITLE
Pressing enter in the data explorer search box does not submit the search in IE 11

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#5032] opened 2016-07-07 10:18 UTC
#### Reproduce

Enter text in the search box in the data explorer and press enter
#### Expected

A search is submitted
#### Observed

Nothing happens

Tested on IE11, Molgenis 1.21.1

**Comment by bartcharbon** [comment] 2016-09-01 11:49
These kind of problems are known for IE11 (and other versions)

I tried some workarounds (listen to key events and clicking programatically, add name to <divs>, change <div> to <form>) without any of them working. 

I propose "won't fix" because the problem seems to originate from the browser and not molgenis.

**Comment by bartcharbon** [comment] 2016-12-05 14:23
still broken in 21.3 (on the VKGL server)

**Comment by mswertz** [comment] 2018-09-12 21:05
I just tested this on UMCG workplace using IE11. Cannot reproduce anymore.

**Closed** 2018-09-12 21:05 UTC
Labels: 1.21.1, bug, mod:dataexplorer
