### ISSUE TITLE
Downloaded metadata inconsistent with existing metadata

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#6110] opened 2017-04-24 12:42 UTC
### How to Reproduce
Do the emx downloader test sheet

### Expected behavior
Downloaded metadata is compatible with the original metadata

### Observed behavior
Test case 4 fails, the original EMX file refuses to upload in add/update mode, complaining that the metadata is incompatible, making the download / update roundtrip harder than it needs to be.

Manual inspection hows that the values of auto, lookupAttribute and labelAttribute are different from the original values. The metadata reported by /meta gives the derived values, but the compatibility check doesn't take that into account.

**Comment by mswertz** [comment] 2017-05-24 20:54
Expected behavior incorrect?

**Comment by fdlk** [comment] 2017-05-29 09:10
@mswertz updated expected behavior

**Comment by Mark-de-Haan** [comment] 2017-11-22 09:12
Duplicate of #6024

**Closed by Mark-de-Haan** 2017-11-22 09:12 UTC
Labels: 4.0, bug, mod:data-importer, priority-first
