### ISSUE TITLE
Reindexing of single entity assumes ID type is String

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#5174] opened 2016-08-12 10:02 UTC
#### Reproduce

Import [bbmri_imaging_datamodel.xlsx](https://github.com/molgenis/molgenis/files/415051/bbmri_imaging_datamodel.xlsx)
- Dataexplorer -> imaging_data
- Edit an entity and change a field
#### Expected

Update succeeds without errors
#### Observed

```
12:01:12.841 [pool-1-thread-1] ERROR o.m.d.e.reindex.job.ReindexJob - Reindex job failed
com.google.common.util.concurrent.UncheckedExecutionException: org.molgenis.data.MolgenisDataException: Attribute [id] query value is of type [String] instead of [Integer]
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[guava-16.0.1.jar:na]
    at com.google.common.cache.LocalCache.get(LocalCache.java:3934) ~[guava-16.0.1.jar:na]
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) ~[guava-16.0.1.jar:na]
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) ~[guava-16.0.1.jar:na]
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) ~[guava-16.0.1.jar:na]
    at org.molgenis.data.cache.l2.L2Cache.get(L2Cache.java:91) ~[molgenis-data-cache-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.cache.l2.L2CacheRepositoryDecorator.findOneById(L2CacheRepositoryDecorator.java:74) ~[molgenis-data-cache-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.cache.l1.L1CacheRepositoryDecorator.findOneById(L1CacheRepositoryDecorator.java:82) ~[molgenis-data-cache-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.elasticsearch.IndexedRepositoryDecorator.findOneById(IndexedRepositoryDecorator.java:111) ~[molgenis-data-elasticsearch-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.AbstractRepositoryDecorator.findOneById(AbstractRepositoryDecorator.java:91) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.EntityReferenceResolverDecorator.findOneById(EntityReferenceResolverDecorator.java:114) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.listeners.EntityListenerRepositoryDecorator.findOneById(EntityListenerRepositoryDecorator.java:104) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.validation.RepositoryValidationDecorator.findOneById(RepositoryValidationDecorator.java:156) ~[molgenis-data-validation-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.AutoValueRepositoryDecorator.findOneById(AutoValueRepositoryDecorator.java:135) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.RepositorySecurityDecorator.findOneById(RepositorySecurityDecorator.java:97) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.support.DataServiceImpl.findOneById(DataServiceImpl.java:79) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>) ~[spring-core-4.1.8.RELEASE.jar:na]
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.8.RELEASE.jar:4.1.8.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649) ~[spring-aop-4.1.8.RELEASE.jar:4.1.8.RELEASE]
    at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$24930b8f.findOneById(<generated>) ~[spring-core-4.1.8.RELEASE.jar:na]
    at org.molgenis.data.elasticsearch.reindex.job.ReindexJob.rebuildIndexOneEntity(ReindexJob.java:198) [molgenis-data-elasticsearch-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.elasticsearch.reindex.job.ReindexJob.performAction(ReindexJob.java:132) [molgenis-data-elasticsearch-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.elasticsearch.reindex.job.ReindexJob.performReindexActions(ReindexJob.java:88) [molgenis-data-elasticsearch-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.elasticsearch.reindex.job.ReindexJob.call(ReindexJob.java:62) [molgenis-data-elasticsearch-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.elasticsearch.reindex.job.ReindexJob.call(ReindexJob.java:36) [molgenis-data-elasticsearch-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.jobs.Job.runWithAuthentication(Job.java:89) [molgenis-jobs-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.jobs.Job.tryRunWithAuthentication(Job.java:74) [molgenis-jobs-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.jobs.Job.call(Job.java:44) [molgenis-jobs-2.0.0-SNAPSHOT.jar:na]
    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_71]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_71]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_71]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_71]
Caused by: org.molgenis.data.MolgenisDataException: Attribute [id] query value is of type [String] instead of [Integer]
    at org.molgenis.data.postgresql.PostgreSqlUtils.getPostgreSqlQueryValue(PostgreSqlUtils.java:192) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.postgresql.PostgreSqlQueryGenerator.getSqlWhere(PostgreSqlQueryGenerator.java:574) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.postgresql.PostgreSqlQueryGenerator.getSqlSelect(PostgreSqlQueryGenerator.java:300) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.postgresql.PostgreSqlRepository$2.getBatch(PostgreSqlRepository.java:406) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.support.BatchingQueryResult.getBatch(BatchingQueryResult.java:36) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.support.BatchingQueryResult.getBatch(BatchingQueryResult.java:14) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.util.BatchingIterable$1.nextBatch(BatchingIterable.java:138) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.util.BatchingIterable$1.hasNext(BatchingIterable.java:58) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
    at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811) ~[na:1.8.0_71]
    at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[na:1.8.0_71]
    at org.molgenis.data.postgresql.PostgreSqlRepository.findOne(PostgreSqlRepository.java:165) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.postgresql.PostgreSqlRepository.findOneById(PostgreSqlRepository.java:179) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.cache.l2.L2Cache$1.load(L2Cache.java:185) ~[molgenis-data-cache-2.0.0-SNAPSHOT.jar:na]
    at org.molgenis.data.cache.l2.L2Cache$1.load(L2Cache.java:176) ~[molgenis-data-cache-2.0.0-SNAPSHOT.jar:na]
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) ~[guava-16.0.1.jar:na]
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) ~[guava-16.0.1.jar:na]
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) ~[guava-16.0.1.jar:na]
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) ~[guava-16.0.1.jar:na]
    ... 31 common frames omitted
```

**Comment by dennishendriksen** [comment] 2016-08-16 14:52
Cannot reproduce, data imports and reindex successfully. Probably fixed by another fix.

**Comment by fdlk** [comment] 2016-08-16 16:33
I ran into this on molgenis01 today. Could of course still be solved by one of today's fixes but I seriously doubt it.

**Comment by jjettenn** [comment] 2016-10-05 14:36
Upload "emx_all_datatypes.xlsx"
Add: ref6, label6
Add new ref to TypeTest
Error on server: Caused by: org.molgenis.data.MolgenisDataException:  Attribute [id] query value is of type [String] instead of [Integer]

**Comment by dennishendriksen** [comment] 2016-10-26 13:37
@jjettenn I cannot reproduce this issue with your example. When you say 'Add new ref to TypeTest' do you mean adding a new row in the dataexplorer table? Because that is what I tried.

**Comment by jjettenn** [comment] 2016-11-30 13:22
Cannot reproduce, probably already fixed

**Closed by jjettenn** 2016-11-30 13:22 UTC
Labels: 2.0-RC, bug
