### ISSUE TITLE
'New' molgenis logo renders incorrectly on ie.11 ( via umcg WOM env) 

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#8156] opened 2019-01-16 11:44 UTC
### How to Reproduce
View molgenis using ie.11 ( is used the umcg remote desktop enviroment)

### Expected behavior
![screenshot 2019-01-16 at 12 41 46](https://user-images.githubusercontent.com/1277621/51247074-542f1b80-198c-11e9-9178-7bf22a788229.png)

### Observed behavior
![logo-issue](https://user-images.githubusercontent.com/1277621/51247090-63ae6480-198c-11e9-87d3-359c1105b02a.PNG)

**Comment by marikaris** [comment] 2019-01-22 11:20
All logo's were resized in PR #8173, so please check if this is fixed after merge

**Comment by marikaris** [comment] 2019-03-25 09:42
Possibly fixed in #8173, but no one checked. Cannot reproduce:
<img width="296" alt="Screen Shot 2019-03-25 at 10 40 32" src="https://user-images.githubusercontent.com/10075439/54909499-a63f7080-4eea-11e9-9b84-668aaca18d76.png">
Seems just as pixly as the microsoft logo:
<img width="150" alt="Screen Shot 2019-03-25 at 10 40 40" src="https://user-images.githubusercontent.com/10075439/54909514-b0616f00-4eea-11e9-9a09-8d845c551927.png">
The resolution of the WOM is not very good.

**Comment by marikaris** [comment] 2019-03-25 10:04
Cannot reproduce

**Closed by marikaris** 2019-03-25 10:04 UTC
Labels: ie11, master, mod:core-ui
