### ISSUE TITLE
snpEff annotator creates an empty compound attribute called 'snpEff' in the EFFECTS entity

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5241] opened 2016-09-02 10:17 UTC
#### Reproduce

Upload vcf.
Annotate with snpEff.
Open the effects entity
#### Expected

Effects entity contains the effect attributes
#### Observed

Effects entity also contains an empty compound attribute called 'snpEff'

**Comment by dennishendriksen** [comment] 2016-11-17 08:11
Cannot reproduce in 1.21.5 with the VCF in this zip: [test.zip](https://github.com/molgenis/molgenis/files/596836/test.zip). Tried to reproduce in 2.0-RC with the same VCF, but ran into issue #5565

**Comment by dennishendriksen** [comment] 2016-11-18 07:25
Fixed by #5565

**Closed** 2016-11-30 12:53 UTC
Labels: 2.0-RC, bug, mod:data-annotators
